---
- name: "creating aws infra using ansible"
  hosts: localhost
  vars:
    access_key: "*********"
    secret_key: "******************"
    region: "ap-south-1"
  
  tasks:
    - name: "amazon fetching ec2 info"
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        filters:
          "tag:project" : "zomato"
          instance-state-name: [ "running"]

      register: ec2

    - debug: 
        var: ec2

    
    - name: "amazon - creating dynamic inventory"
      add_host:
        hostname: "{{ item.public_ip_address }}"
        ansible_host: "{{ item.public_ip_address }}"
        ansible_ssh_port: 22
        groups:
          - backends
        ansible_ssh_private_key_file: "bibin.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items: "{{ ec2.instances }}"

- name: "deploying from github"
  hosts: backends
  become: true
  serial: 1
  vars:
    packages:
      - httpd
      - php
      - git
    repo: https://github.com/bibin521/crispy_for_demo.git


  tasks:

    - name: "package installation"
      yum:
        name: "{{ packages }}"
        state: present
    - name: "cloning repo {{ repo }}"
      git:
        repo: "{{ repo }}"
        dest: "/var/website"
      register: gitstatus

    - name: "backend off loading from elb "
      when: gitstatus.changed
      file:
        path: "/var/www/html/index.html"
        mode: 0000

    - name: "waiting foe connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 30

    - name: "updating site contents"
      when: gitstatus.changed
      copy:
        src: "/var/website/"
        dest: "/var/www/html/"
        remote_src: true
        owner: apache
        group: apache


    - name: "loading backend to elb"
      when: gitstatus.changed
      file:
        path: "/var/www/html/index.html"
        mode: 0644

    - name: "waiting foe connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 30

